version: 2
dependencies:
  pre:
   - sudo apt-get update
   - sudo apt-get install build-essential g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev 
   - sudo apt-get install libboost-all-dev
jobs:
    build:
      override:
        - make all 
    test:
      override:
        - cd src/test/test_code;make all
        - cd src/test/test_code;./bartenderUnitTests

